### PR TITLE
fix: update PIN prompts to specify Cove PIN and TapSigner PIN

### LINKED ISSUE #512: Differentiate Cove PIN from TapSigner PIN prompts
## Problem
When using a TapSigner, it's difficult to differentiate between when the app is asking for the Cove wallet PIN vs the hardware PIN. Both show generic "Enter PIN" title.

## Current Behavior
- `LockView.kt` shows "Enter Pin"
- `TapSignerEnterPinView.kt` shows "Enter PIN"

## Proposed Solution
Update titles to be explicit:
- Cove PIN: "Enter Cove PIN" or "Unlock Cove Wallet"
- TapSigner: "Enter TapSigner PIN"

## Files
- `android/app/src/main/java/org/bitcoinppl/cove/views/LockView.kt:194`
- `android/app/src/main/java/org/bitcoinppl/cove/flows/TapSignerFlow/TapSignerEnterPinView.kt:122`

## iOS Status
Same issue exists - uses generic "Enter PIN" for both contexts.

### PR DESCRIPTION
**Pull request by kartikangiras**
## Issue
Fixes #512 

## Changes
- Android lock screen PIN entry now shows Enter Cove PIN in the lock keypad flow
- Android biometric fallback button now says Enter Cove PIN
- Android TapSigner PIN screen title now says Enter TapSigner PIN
- iOS lock screen keypad title now says Enter Cove PIN
- iOS biometric fallback button now says Enter Cove PIN
- iOS TapSigner PIN screen title now says Enter TapSigner PIN

## Summary by CodeRabbit

* **Style**
  * Updated PIN entry labels on Android and iOS: the main lock screen now shows "Enter Cove PIN" instead of "Enter PIN", biometric screens reflect the same wording, and the TapSigner authentication flow now displays "Enter TAPSIGNER PIN".

### CODE REVIEW

File: android/app/src/main/java/org/bitcoinppl/cove/flows/TapSignerFlow/TapSignerEnterPinView.kt [hunk 1]
```diff
@@ -119,7 +119,7 @@ fun TapSignerEnterPinView(
             verticalArrangement = Arrangement.spacedBy(20.dp),
         ) {
             Text(
-                text = "Enter PIN",
+                text = "Enter TapSigner PIN",
```
Comment (praveenperera) [inline android/app/src/main/java/org/bitcoinppl/cove/flows/TapSignerFlow/TapSignerEnterPinView.kt]: TAPSIGNER (all caps)

**Review by praveenperera — CHANGES_REQUESTED** [review]

File: android/app/src/main/java/org/bitcoinppl/cove/flows/TapSignerFlow/TapSignerEnterPinView.kt (hunk 1 above)
Comment (kartikangiras) [reply android/app/src/main/java/org/bitcoinppl/cove/flows/TapSignerFlow/TapSignerEnterPinView.kt]: done

**Comment by praveenperera** [comment]
squash commits and make the commit message follow rules from CONTRIBUTING.md

**Comment by kartikangiras** [comment]
> squash commits and make the commit message follow rules from CONTRIBUTING.md

Squashed into 1 commit with updated commit message

**Comment by praveenperera** [comment]
Thank you @kartikangiras merged

**Review by praveenperera — APPROVED** [review]
